const mongoose = require('mongoose');
const Species = require('./models/Species');

const species = [
  // ── MAMMALS ──────────────────────────────────────────────────────────────
  { commonName: 'Mantled Howler Monkey', scientificName: 'Alouatta palliata', group: 'Mammal' },
  { commonName: 'White-faced Capuchin', scientificName: 'Cebus imitator', group: 'Mammal' },
  { commonName: "Geoffroy's Spider Monkey", scientificName: 'Ateles geoffroyi', group: 'Mammal' },
  { commonName: 'Central American Squirrel Monkey', scientificName: 'Saimiri oerstedii', group: 'Mammal' },
  { commonName: 'Three-toed Sloth', scientificName: 'Bradypus variegatus', group: 'Mammal' },
  { commonName: "Hoffmann's Two-toed Sloth", scientificName: 'Choloepus hoffmanni', group: 'Mammal' },
  { commonName: 'Nine-banded Armadillo', scientificName: 'Dasypus novemcinctus', group: 'Mammal' },
  { commonName: 'Giant Anteater', scientificName: 'Myrmecophaga tridactyla', group: 'Mammal' },
  { commonName: 'Northern Tamandua', scientificName: 'Tamandua mexicana', group: 'Mammal' },
  { commonName: 'Silky Anteater', scientificName: 'Cyclopes didactylus', group: 'Mammal' },
  { commonName: "Baird's Tapir", scientificName: 'Tapirus bairdii', group: 'Mammal' },
  { commonName: 'White-lipped Peccary', scientificName: 'Tayassu pecari', group: 'Mammal' },
  { commonName: 'Collared Peccary', scientificName: 'Pecari tajacu', group: 'Mammal' },
  { commonName: 'Red Brocket Deer', scientificName: 'Mazama americana', group: 'Mammal' },
  { commonName: 'White-tailed Deer', scientificName: 'Odocoileus virginianus', group: 'Mammal' },
  { commonName: 'Jaguar', scientificName: 'Panthera onca', group: 'Mammal' },
  { commonName: 'Puma', scientificName: 'Puma concolor', group: 'Mammal' },
  { commonName: 'Ocelot', scientificName: 'Leopardus pardalis', group: 'Mammal' },
  { commonName: 'Margay', scientificName: 'Leopardus wiedii', group: 'Mammal' },
  { commonName: 'Oncilla', scientificName: 'Leopardus tigrinus', group: 'Mammal' },
  { commonName: 'Jaguarundi', scientificName: 'Herpailurus yagouaroundi', group: 'Mammal' },
  { commonName: 'Neotropical River Otter', scientificName: 'Lontra longicaudis', group: 'Mammal' },
  { commonName: 'Giant River Otter', scientificName: 'Pteronura brasiliensis', group: 'Mammal' },
  { commonName: 'Tayra', scientificName: 'Eira barbara', group: 'Mammal' },
  { commonName: 'Greater Grison', scientificName: 'Galictis vittata', group: 'Mammal' },
  { commonName: 'Striped Hog-nosed Skunk', scientificName: 'Conepatus semistriatus', group: 'Mammal' },
  { commonName: 'Spotted Skunk', scientificName: 'Spilogale angustifrons', group: 'Mammal' },
  { commonName: 'Northern Raccoon', scientificName: 'Procyon lotor', group: 'Mammal' },
  { commonName: 'Crab-eating Raccoon', scientificName: 'Procyon cancrivorus', group: 'Mammal' },
  { commonName: 'White-nosed Coati', scientificName: 'Nasua narica', group: 'Mammal' },
  { commonName: 'Kinkajou', scientificName: 'Potos flavus', group: 'Mammal' },
  { commonName: 'Olingo', scientificName: 'Bassaricyon gabbii', group: 'Mammal' },
  { commonName: 'Coyote', scientificName: 'Canis latrans', group: 'Mammal' },
  { commonName: 'Gray Fox', scientificName: 'Urocyon cinereoargenteus', group: 'Mammal' },
  { commonName: 'Common Opossum', scientificName: 'Didelphis marsupialis', group: 'Mammal' },
  { commonName: 'Virginia Opossum', scientificName: 'Didelphis virginiana', group: 'Mammal' },
  { commonName: 'Water Opossum', scientificName: 'Chironectes minimus', group: 'Mammal' },
  { commonName: "Robinson's Mouse Opossum", scientificName: 'Marmosa robinsoni', group: 'Mammal' },
  { commonName: 'Central American Woolly Opossum', scientificName: 'Caluromys derbianus', group: 'Mammal' },
  { commonName: 'Variegated Squirrel', scientificName: 'Sciurus variegatoides', group: 'Mammal' },
  { commonName: 'Red-tailed Squirrel', scientificName: 'Sciurus granatensis', group: 'Mammal' },
  { commonName: "Alfaro's Pygmy Squirrel", scientificName: 'Microsciurus alfari', group: 'Mammal' },
  { commonName: "Deppe's Squirrel", scientificName: 'Sciurus deppei', group: 'Mammal' },
  { commonName: 'Mexican Hairy Dwarf Porcupine', scientificName: 'Coendou mexicanus', group: 'Mammal' },
  { commonName: 'Central American Agouti', scientificName: 'Dasyprocta punctata', group: 'Mammal' },
  { commonName: 'Paca', scientificName: 'Cuniculus paca', group: 'Mammal' },
  { commonName: 'Capybara', scientificName: 'Hydrochoerus hydrochaeris', group: 'Mammal' },
  { commonName: 'Common Spiny Rat', scientificName: 'Proechimys semispinosus', group: 'Mammal' },
  { commonName: 'Hispid Cotton Rat', scientificName: 'Sigmodon hispidus', group: 'Mammal' },
  { commonName: 'Forest Spiny Pocket Mouse', scientificName: 'Heteromys desmarestianus', group: 'Mammal' },
  { commonName: 'Greater White-lined Bat', scientificName: 'Saccopteryx bilineata', group: 'Mammal' },
  { commonName: 'Ghost Bat', scientificName: 'Diclidurus albus', group: 'Mammal' },
  { commonName: 'Proboscis Bat', scientificName: 'Rhynchonycteris naso', group: 'Mammal' },
  { commonName: 'Greater Fishing Bat', scientificName: 'Noctilio leporinus', group: 'Mammal' },
  { commonName: 'Common Vampire Bat', scientificName: 'Desmodus rotundus', group: 'Mammal' },
  { commonName: 'Hairy-legged Vampire Bat', scientificName: 'Diphylla ecaudata', group: 'Mammal' },
  { commonName: 'White-winged Vampire Bat', scientificName: 'Diaemus youngi', group: 'Mammal' },
  { commonName: 'Jamaican Fruit Bat', scientificName: 'Artibeus jamaicensis', group: 'Mammal' },
  { commonName: 'Great Fruit-eating Bat', scientificName: 'Artibeus lituratus', group: 'Mammal' },
  { commonName: 'Tent-making Bat', scientificName: 'Uroderma bilobatum', group: 'Mammal' },
  { commonName: 'Honduran White Bat', scientificName: 'Ectophylla alba', group: 'Mammal' },
  { commonName: 'Common Long-tongued Bat', scientificName: 'Glossophaga soricina', group: 'Mammal' },
  { commonName: 'Fringe-lipped Bat', scientificName: 'Trachops cirrhosus', group: 'Mammal' },
  { commonName: 'Brazilian Free-tailed Bat', scientificName: 'Tadarida brasiliensis', group: 'Mammal' },
  { commonName: 'Velvety Free-tailed Bat', scientificName: 'Molossus molossus', group: 'Mammal' },
  { commonName: 'Bottlenose Dolphin', scientificName: 'Tursiops truncatus', group: 'Mammal' },
  { commonName: 'Spinner Dolphin', scientificName: 'Stenella longirostris', group: 'Mammal' },
  { commonName: 'Humpback Whale', scientificName: 'Megaptera novaeangliae', group: 'Mammal' },
  { commonName: 'West Indian Manatee', scientificName: 'Trichechus manatus', group: 'Mammal' },
  { commonName: 'Sperm Whale', scientificName: 'Physeter macrocephalus', group: 'Mammal' },

  // ── REPTILES ─────────────────────────────────────────────────────────────
  { commonName: 'American Crocodile', scientificName: 'Crocodylus acutus', group: 'Reptile' },
  { commonName: 'Spectacled Caiman', scientificName: 'Caiman crocodilus', group: 'Reptile' },
  { commonName: 'Green Iguana', scientificName: 'Iguana iguana', group: 'Reptile' },
  { commonName: 'Black Spiny-tailed Iguana', scientificName: 'Ctenosaura similis', group: 'Reptile' },
  { commonName: 'Green Basilisk', scientificName: 'Basiliscus plumifrons', group: 'Reptile' },
  { commonName: 'Brown Basilisk', scientificName: 'Basiliscus vittatus', group: 'Reptile' },
  { commonName: 'Common Basilisk', scientificName: 'Basiliscus basiliscus', group: 'Reptile' },
  { commonName: 'Helmeted Iguana', scientificName: 'Corytophanes cristatus', group: 'Reptile' },
  { commonName: 'Slender Anole', scientificName: 'Norops limifrons', group: 'Reptile' },
  { commonName: 'Ground Anole', scientificName: 'Norops humilis', group: 'Reptile' },
  { commonName: 'Forest Anole', scientificName: 'Norops biporcatus', group: 'Reptile' },
  { commonName: 'Central American Whiptail', scientificName: 'Ameiva festiva', group: 'Reptile' },
  { commonName: 'Giant Ameiva', scientificName: 'Ameiva ameiva', group: 'Reptile' },
  { commonName: 'Turnip-tailed Gecko', scientificName: 'Thecadactylus solimoensis', group: 'Reptile' },
  { commonName: 'Yellow-headed Gecko', scientificName: 'Gonatodes albogularis', group: 'Reptile' },
  { commonName: 'Mourning Gecko', scientificName: 'Lepidodactylus lugubris', group: 'Reptile' },
  { commonName: 'Central American Banded Gecko', scientificName: 'Coleonyx mitratus', group: 'Reptile' },
  { commonName: 'Brown Forest Skink', scientificName: 'Sphenomorphus cherriei', group: 'Reptile' },
  { commonName: 'Bronze-backed Parrot Snake', scientificName: 'Leptophis ahaetulla', group: 'Reptile' },
  { commonName: 'Green Parrot Snake', scientificName: 'Leptophis depressirostris', group: 'Reptile' },
  { commonName: 'Blunthead Tree Snake', scientificName: 'Imantodes cenchoa', group: 'Reptile' },
  { commonName: 'Vine Snake', scientificName: 'Oxybelis aeneus', group: 'Reptile' },
  { commonName: 'Green Vine Snake', scientificName: 'Oxybelis fulgidus', group: 'Reptile' },
  { commonName: 'Indigo Snake', scientificName: 'Drymarchon melanurus', group: 'Reptile' },
  { commonName: 'Boa Constrictor', scientificName: 'Boa constrictor', group: 'Reptile' },
  { commonName: 'Terciopelo / Fer-de-Lance', scientificName: 'Bothrops asper', group: 'Reptile' },
  { commonName: 'Eyelash Palm Pit Viper', scientificName: 'Bothriechis schlegelii', group: 'Reptile' },
  { commonName: 'Side-striped Palm Pit Viper', scientificName: 'Bothriechis lateralis', group: 'Reptile' },
  { commonName: 'Jumping Pit Viper', scientificName: 'Atropoides mexicanus', group: 'Reptile' },
  { commonName: 'Bushmaster', scientificName: 'Lachesis stenophrys', group: 'Reptile' },
  { commonName: 'Central American Rattlesnake', scientificName: 'Crotalus simus', group: 'Reptile' },
  { commonName: 'Hognose Pit Viper', scientificName: 'Porthidium nasutum', group: 'Reptile' },
  { commonName: 'Central American Coral Snake', scientificName: 'Micrurus nigrocinctus', group: 'Reptile' },
  { commonName: "Allen's Coral Snake", scientificName: 'Micrurus alleni', group: 'Reptile' },
  { commonName: "Clark's Coral Snake", scientificName: 'Micrurus clarki', group: 'Reptile' },
  { commonName: 'Central American Mud Turtle', scientificName: 'Kinosternon leucostomum', group: 'Reptile' },
  { commonName: 'White-lipped Mud Turtle', scientificName: 'Kinosternon albogulare', group: 'Reptile' },
  { commonName: 'Leatherback Sea Turtle', scientificName: 'Dermochelys coriacea', group: 'Reptile' },
  { commonName: 'Green Sea Turtle', scientificName: 'Chelonia mydas', group: 'Reptile' },
  { commonName: 'Hawksbill Sea Turtle', scientificName: 'Eretmochelys imbricata', group: 'Reptile' },
  { commonName: 'Loggerhead Sea Turtle', scientificName: 'Caretta caretta', group: 'Reptile' },
  { commonName: 'Olive Ridley Sea Turtle', scientificName: 'Lepidochelys olivacea', group: 'Reptile' },
  { commonName: 'Black River Turtle', scientificName: 'Rhinoclemmys funerea', group: 'Reptile' },
  { commonName: 'Brown Wood Turtle', scientificName: 'Rhinoclemmys annulata', group: 'Reptile' },
  { commonName: 'Painted Wood Turtle', scientificName: 'Rhinoclemmys pulcherrima', group: 'Reptile' },
  { commonName: 'Central American Snapping Turtle', scientificName: 'Chelydra acutirostris', group: 'Reptile' },
  { commonName: 'Rainbow Boa', scientificName: 'Epicrates cenchria', group: 'Reptile' },
  { commonName: "Godman's Montane Pit Viper", scientificName: 'Cerrophidion godmani', group: 'Reptile' },

  // ── BIRDS ─────────────────────────────────────────────────────────────────
  { commonName: 'Resplendent Quetzal', scientificName: 'Pharomachrus mocinno', group: 'Bird' },
  { commonName: 'Scarlet Macaw', scientificName: 'Ara macao', group: 'Bird' },
  { commonName: 'Great Green Macaw', scientificName: 'Ara ambiguus', group: 'Bird' },
  { commonName: 'Crimson-fronted Parakeet', scientificName: 'Psittacara finschi', group: 'Bird' },
  { commonName: 'Orange-fronted Parakeet', scientificName: 'Eupsittula canicularis', group: 'Bird' },
  { commonName: 'Brown-hooded Parrot', scientificName: 'Pyrilia haematotis', group: 'Bird' },
  { commonName: 'White-crowned Parrot', scientificName: 'Pionus senilis', group: 'Bird' },
  { commonName: 'Mealy Parrot', scientificName: 'Amazona farinosa', group: 'Bird' },
  { commonName: 'Red-lored Parrot', scientificName: 'Amazona autumnalis', group: 'Bird' },
  { commonName: 'Yellow-naped Parrot', scientificName: 'Amazona auropalliata', group: 'Bird' },
  { commonName: 'Blue-headed Parrot', scientificName: 'Pionus menstruus', group: 'Bird' },
  { commonName: 'Keel-billed Toucan', scientificName: 'Ramphastos sulfuratus', group: 'Bird' },
  { commonName: 'Chestnut-mandibled Toucan', scientificName: 'Ramphastos swainsonii', group: 'Bird' },
  { commonName: 'Collared Aracari', scientificName: 'Pteroglossus torquatus', group: 'Bird' },
  { commonName: 'Fiery-billed Aracari', scientificName: 'Pteroglossus frantzii', group: 'Bird' },
  { commonName: 'Emerald Toucanet', scientificName: 'Aulacorhynchus prasinus', group: 'Bird' },
  { commonName: 'Rufous-tailed Hummingbird', scientificName: 'Amazilia tzacatl', group: 'Bird' },
  { commonName: 'Violet Sabrewing', scientificName: 'Campylopterus hemileucurus', group: 'Bird' },
  { commonName: 'Purple-throated Mountain-gem', scientificName: 'Lampornis calolaemus', group: 'Bird' },
  { commonName: 'Green-crowned Brilliant', scientificName: 'Heliodoxa jacula', group: 'Bird' },
  { commonName: 'Snowcap', scientificName: 'Microchera albocoronata', group: 'Bird' },
  { commonName: 'White-necked Jacobin', scientificName: 'Florisuga mellivora', group: 'Bird' },
  { commonName: 'Long-billed Hermit', scientificName: 'Phaethornis longirostris', group: 'Bird' },
  { commonName: 'Green Hermit', scientificName: 'Phaethornis guy', group: 'Bird' },
  { commonName: 'Crowned Woodnymph', scientificName: 'Thalurania colombica', group: 'Bird' },
  { commonName: 'Scintillant Hummingbird', scientificName: 'Selasphorus scintilla', group: 'Bird' },
  { commonName: 'Volcano Hummingbird', scientificName: 'Selasphorus flammula', group: 'Bird' },
  { commonName: 'Coppery-headed Emerald', scientificName: 'Elvira cupreiceps', group: 'Bird' },
  { commonName: 'Turquoise-browed Motmot', scientificName: 'Eumomota superciliosa', group: 'Bird' },
  { commonName: 'Blue-crowned Motmot', scientificName: 'Momotus coeruliceps', group: 'Bird' },
  { commonName: 'Rufous Motmot', scientificName: 'Baryphthengus martii', group: 'Bird' },
  { commonName: 'Broad-billed Motmot', scientificName: 'Electron platyrhynchum', group: 'Bird' },
  { commonName: 'Ringed Kingfisher', scientificName: 'Megaceryle torquata', group: 'Bird' },
  { commonName: 'Amazon Kingfisher', scientificName: 'Chloroceryle amazona', group: 'Bird' },
  { commonName: 'Green Kingfisher', scientificName: 'Chloroceryle americana', group: 'Bird' },
  { commonName: 'American Pygmy Kingfisher', scientificName: 'Chloroceryle aenea', group: 'Bird' },
  { commonName: 'Rufous-tailed Jacamar', scientificName: 'Galbula ruficauda', group: 'Bird' },
  { commonName: 'White-necked Puffbird', scientificName: 'Notharchus hyperrhynchus', group: 'Bird' },
  { commonName: 'Red-headed Barbet', scientificName: 'Eubucco bourcierii', group: 'Bird' },
  { commonName: 'Prong-billed Barbet', scientificName: 'Semnornis frantzii', group: 'Bird' },
  { commonName: 'Acorn Woodpecker', scientificName: 'Melanerpes formicivorus', group: 'Bird' },
  { commonName: 'Black-cheeked Woodpecker', scientificName: 'Melanerpes pucherani', group: 'Bird' },
  { commonName: "Hoffmann's Woodpecker", scientificName: 'Melanerpes hoffmannii', group: 'Bird' },
  { commonName: 'Pale-billed Woodpecker', scientificName: 'Campephilus guatemalensis', group: 'Bird' },
  { commonName: 'Lineated Woodpecker', scientificName: 'Dryocopus lineatus', group: 'Bird' },
  { commonName: 'Golden-naped Woodpecker', scientificName: 'Melanerpes chrysauchen', group: 'Bird' },
  { commonName: 'Fasciated Antshrike', scientificName: 'Cymbilaimus lineatus', group: 'Bird' },
  { commonName: 'Great Antshrike', scientificName: 'Taraba major', group: 'Bird' },
  { commonName: 'Barred Antshrike', scientificName: 'Thamnophilus doliatus', group: 'Bird' },
  { commonName: 'Chestnut-backed Antbird', scientificName: 'Poliocrania exsul', group: 'Bird' },
  { commonName: 'Spotted Antbird', scientificName: 'Hylophylax naevioides', group: 'Bird' },
  { commonName: 'Bicolored Antbird', scientificName: 'Gymnopithys bicolor', group: 'Bird' },
  { commonName: 'Ocellated Antbird', scientificName: 'Phaenostictus mcleannani', group: 'Bird' },
  { commonName: 'Black-faced Antthrush', scientificName: 'Formicarius analis', group: 'Bird' },
  { commonName: 'Scaled Antpitta', scientificName: 'Grallaria guatimalensis', group: 'Bird' },
  { commonName: 'Three-wattled Bellbird', scientificName: 'Procnias tricarunculatus', group: 'Bird' },
  { commonName: 'Bare-necked Umbrellabird', scientificName: 'Cephalopterus glabricollis', group: 'Bird' },
  { commonName: 'Long-tailed Manakin', scientificName: 'Chiroxiphia linearis', group: 'Bird' },
  { commonName: 'Red-capped Manakin', scientificName: 'Ceratopipra mentalis', group: 'Bird' },
  { commonName: 'White-collared Manakin', scientificName: 'Manacus candei', group: 'Bird' },
  { commonName: 'Orange-collared Manakin', scientificName: 'Manacus aurantiacus', group: 'Bird' },
  { commonName: 'Tropical Kingbird', scientificName: 'Tyrannus melancholicus', group: 'Bird' },
  { commonName: 'Fork-tailed Flycatcher', scientificName: 'Tyrannus savana', group: 'Bird' },
  { commonName: 'Great Kiskadee', scientificName: 'Pitangus sulphuratus', group: 'Bird' },
  { commonName: 'Social Flycatcher', scientificName: 'Myiozetetes similis', group: 'Bird' },
  { commonName: 'Boat-billed Flycatcher', scientificName: 'Megarynchus pitangua', group: 'Bird' },
  { commonName: 'Royal Flycatcher', scientificName: 'Onychorhynchus coronatus', group: 'Bird' },
  { commonName: 'Tufted Flycatcher', scientificName: 'Mitrephanes phaeocercus', group: 'Bird' },
  { commonName: 'Common Tody-Flycatcher', scientificName: 'Todirostrum cinereum', group: 'Bird' },
  { commonName: 'Torrent Tyrannulet', scientificName: 'Serpophaga cinerea', group: 'Bird' },
  { commonName: 'Ochre-bellied Flycatcher', scientificName: 'Mionectes oleagineus', group: 'Bird' },
  { commonName: 'Brown Jay', scientificName: 'Psilorhinus morio', group: 'Bird' },
  { commonName: 'White-throated Magpie-Jay', scientificName: 'Calocitta formosa', group: 'Bird' },
  { commonName: 'Azure-hooded Jay', scientificName: 'Cyanolyca cucullata', group: 'Bird' },
  { commonName: 'Silvery-throated Jay', scientificName: 'Cyanolyca argentigula', group: 'Bird' },
  { commonName: 'Gray-breasted Martin', scientificName: 'Progne chalybea', group: 'Bird' },
  { commonName: 'Blue-and-white Swallow', scientificName: 'Pygochelidon cyanoleuca', group: 'Bird' },
  { commonName: 'Mangrove Swallow', scientificName: 'Tachycineta albilinea', group: 'Bird' },
  { commonName: 'Barn Swallow', scientificName: 'Hirundo rustica', group: 'Bird' },
  { commonName: 'Band-backed Wren', scientificName: 'Campylorhynchus zonatus', group: 'Bird' },
  { commonName: 'Rufous-naped Wren', scientificName: 'Campylorhynchus rufinucha', group: 'Bird' },
  { commonName: 'Bay Wren', scientificName: 'Cantorchilus nigricapillus', group: 'Bird' },
  { commonName: 'House Wren', scientificName: 'Troglodytes aedon', group: 'Bird' },
  { commonName: 'Ochraceous Wren', scientificName: 'Troglodytes ochraceus', group: 'Bird' },
  { commonName: 'Timberline Wren', scientificName: 'Thryorchilus browni', group: 'Bird' },
  { commonName: 'White-breasted Wood-Wren', scientificName: 'Henicorhina leucosticta', group: 'Bird' },
  { commonName: 'Gray-breasted Wood-Wren', scientificName: 'Henicorhina leucophrys', group: 'Bird' },
  { commonName: 'Song Wren', scientificName: 'Cyphorhinus phaeocephalus', group: 'Bird' },
  { commonName: 'Black-faced Solitaire', scientificName: 'Myadestes melanops', group: 'Bird' },
  { commonName: 'Orange-billed Nightingale-Thrush', scientificName: 'Catharus aurantiirostris', group: 'Bird' },
  { commonName: "Ruddy-capped Nightingale-Thrush", scientificName: 'Catharus frantzii', group: 'Bird' },
  { commonName: "Swainson's Thrush", scientificName: 'Catharus ustulatus', group: 'Bird' },
  { commonName: 'Wood Thrush', scientificName: 'Hylocichla mustelina', group: 'Bird' },
  { commonName: 'Clay-colored Thrush', scientificName: 'Turdus grayi', group: 'Bird' },
  { commonName: 'Mountain Thrush', scientificName: 'Turdus plebejus', group: 'Bird' },
  { commonName: 'Sooty Thrush', scientificName: 'Turdus nigrescens', group: 'Bird' },
  { commonName: 'Long-tailed Silky-Flycatcher', scientificName: 'Ptiliogonys caudatus', group: 'Bird' },
  { commonName: 'Cedar Waxwing', scientificName: 'Bombycilla cedrorum', group: 'Bird' },
  { commonName: 'Golden-winged Warbler', scientificName: 'Vermivora chrysoptera', group: 'Bird' },
  { commonName: 'Yellow Warbler', scientificName: 'Setophaga petechia', group: 'Bird' },
  { commonName: 'Blackburnian Warbler', scientificName: 'Setophaga fusca', group: 'Bird' },
  { commonName: 'American Redstart', scientificName: 'Setophaga ruticilla', group: 'Bird' },
  { commonName: 'Ovenbird', scientificName: 'Seiurus aurocapilla', group: 'Bird' },
  { commonName: 'Northern Waterthrush', scientificName: 'Parkesia noveboracensis', group: 'Bird' },
  { commonName: 'Wilson\'s Warbler', scientificName: 'Cardellina pusilla', group: 'Bird' },
  { commonName: 'Canada Warbler', scientificName: 'Cardellina canadensis', group: 'Bird' },
  { commonName: 'Slate-throated Redstart', scientificName: 'Myioborus miniatus', group: 'Bird' },
  { commonName: 'Collared Redstart', scientificName: 'Myioborus torquatus', group: 'Bird' },
  { commonName: 'Buff-rumped Warbler', scientificName: 'Myiothlypis fulvicauda', group: 'Bird' },
  { commonName: 'Flame-throated Warbler', scientificName: 'Oreothlypis gutturalis', group: 'Bird' },
  { commonName: 'Bananaquit', scientificName: 'Coereba flaveola', group: 'Bird' },
  { commonName: 'Blue-gray Tanager', scientificName: 'Thraupis episcopus', group: 'Bird' },
  { commonName: 'Palm Tanager', scientificName: 'Thraupis palmarum', group: 'Bird' },
  { commonName: 'Bay-headed Tanager', scientificName: 'Tangara gyrola', group: 'Bird' },
  { commonName: 'Emerald Tanager', scientificName: 'Tangara florida', group: 'Bird' },
  { commonName: 'Silver-throated Tanager', scientificName: 'Tangara icterocephala', group: 'Bird' },
  { commonName: 'Spangle-cheeked Tanager', scientificName: 'Tangara dowii', group: 'Bird' },
  { commonName: 'Golden-hooded Tanager', scientificName: 'Stilpnia larvata', group: 'Bird' },
  { commonName: 'Scarlet-rumped Tanager', scientificName: 'Ramphocelus passerinii', group: 'Bird' },
  { commonName: "Cherrie's Tanager", scientificName: 'Ramphocelus costaricensis', group: 'Bird' },
  { commonName: 'Crimson-collared Tanager', scientificName: 'Ramphocelus sanguinolentus', group: 'Bird' },
  { commonName: 'Summer Tanager', scientificName: 'Piranga rubra', group: 'Bird' },
  { commonName: 'Scarlet Tanager', scientificName: 'Piranga olivacea', group: 'Bird' },
  { commonName: 'Flame-colored Tanager', scientificName: 'Piranga bidentata', group: 'Bird' },
  { commonName: 'Red-legged Honeycreeper', scientificName: 'Cyanerpes cyaneus', group: 'Bird' },
  { commonName: 'Green Honeycreeper', scientificName: 'Chlorophanes spiza', group: 'Bird' },
  { commonName: 'Blue Dacnis', scientificName: 'Dacnis cayana', group: 'Bird' },
  { commonName: 'Scarlet-thighed Dacnis', scientificName: 'Dacnis venusta', group: 'Bird' },
  { commonName: 'Variable Seedeater', scientificName: 'Sporophila corvina', group: 'Bird' },
  { commonName: 'White-collared Seedeater', scientificName: 'Sporophila torqueola', group: 'Bird' },
  { commonName: 'Large-footed Finch', scientificName: 'Pezopetes capitalis', group: 'Bird' },
  { commonName: 'Yellow-thighed Finch', scientificName: 'Pselliophorus tibialis', group: 'Bird' },
  { commonName: 'Sooty-capped Bush Tanager', scientificName: 'Chlorospingus pileatus', group: 'Bird' },
  { commonName: 'Common Bush Tanager', scientificName: 'Chlorospingus flavopectus', group: 'Bird' },
  { commonName: 'Rose-breasted Grosbeak', scientificName: 'Pheucticus ludovicianus', group: 'Bird' },
  { commonName: 'Blue-black Grosbeak', scientificName: 'Cyanoloxia cyanoides', group: 'Bird' },
  { commonName: 'Indigo Bunting', scientificName: 'Passerina cyanea', group: 'Bird' },
  { commonName: 'Painted Bunting', scientificName: 'Passerina ciris', group: 'Bird' },
  { commonName: 'Eastern Meadowlark', scientificName: 'Sturnella magna', group: 'Bird' },
  { commonName: 'Melodious Blackbird', scientificName: 'Dives dives', group: 'Bird' },
  { commonName: 'Great-tailed Grackle', scientificName: 'Quiscalus mexicanus', group: 'Bird' },
  { commonName: 'Bronzed Cowbird', scientificName: 'Molothrus aeneus', group: 'Bird' },
  { commonName: 'Giant Cowbird', scientificName: 'Molothrus oryzivorus', group: 'Bird' },
  { commonName: 'Montezuma Oropendola', scientificName: 'Psarocolius montezuma', group: 'Bird' },
  { commonName: 'Chestnut-headed Oropendola', scientificName: 'Psarocolius wagleri', group: 'Bird' },
  { commonName: 'Baltimore Oriole', scientificName: 'Icterus galbula', group: 'Bird' },
  { commonName: 'Yellow-tailed Oriole', scientificName: 'Icterus mesomelas', group: 'Bird' },
  { commonName: 'Scarlet-rumped Cacique', scientificName: 'Cacicus uropygialis', group: 'Bird' },
  { commonName: 'Black Vulture', scientificName: 'Coragyps atratus', group: 'Bird' },
  { commonName: 'Turkey Vulture', scientificName: 'Cathartes aura', group: 'Bird' },
  { commonName: 'King Vulture', scientificName: 'Sarcoramphus papa', group: 'Bird' },
  { commonName: 'Osprey', scientificName: 'Pandion haliaetus', group: 'Bird' },
  { commonName: 'Snail Kite', scientificName: 'Rostrhamus sociabilis', group: 'Bird' },
  { commonName: 'Swallow-tailed Kite', scientificName: 'Elanoides forficatus', group: 'Bird' },
  { commonName: 'White-tailed Kite', scientificName: 'Elanus leucurus', group: 'Bird' },
  { commonName: 'Sharp-shinned Hawk', scientificName: 'Accipiter striatus', group: 'Bird' },
  { commonName: 'Broad-winged Hawk', scientificName: 'Buteo platypterus', group: 'Bird' },
  { commonName: "Swainson's Hawk", scientificName: 'Buteo swainsoni', group: 'Bird' },
  { commonName: 'White Hawk', scientificName: 'Pseudastur albicollis', group: 'Bird' },
  { commonName: 'Gray Hawk', scientificName: 'Buteo plagiatus', group: 'Bird' },
  { commonName: 'Roadside Hawk', scientificName: 'Rupornis magnirostris', group: 'Bird' },
  { commonName: 'Black Hawk-Eagle', scientificName: 'Spizaetus tyrannus', group: 'Bird' },
  { commonName: 'Ornate Hawk-Eagle', scientificName: 'Spizaetus ornatus', group: 'Bird' },
  { commonName: 'Harpy Eagle', scientificName: 'Harpia harpyja', group: 'Bird' },
  { commonName: 'Crested Eagle', scientificName: 'Morphnus guianensis', group: 'Bird' },
  { commonName: 'Great Black Hawk', scientificName: 'Buteogallus urubitinga', group: 'Bird' },
  { commonName: 'Common Black Hawk', scientificName: 'Buteogallus anthracinus', group: 'Bird' },
  { commonName: 'Laughing Falcon', scientificName: 'Herpetotheres cachinnans', group: 'Bird' },
  { commonName: 'Collared Forest Falcon', scientificName: 'Micrastur semitorquatus', group: 'Bird' },
  { commonName: 'Bat Falcon', scientificName: 'Falco rufigularis', group: 'Bird' },
  { commonName: 'Peregrine Falcon', scientificName: 'Falco peregrinus', group: 'Bird' },
  { commonName: 'American Kestrel', scientificName: 'Falco sparverius', group: 'Bird' },
  { commonName: 'Great Curassow', scientificName: 'Crax rubra', group: 'Bird' },
  { commonName: 'Black Guan', scientificName: 'Chamaepetes unicolor', group: 'Bird' },
  { commonName: 'Crested Guan', scientificName: 'Penelope purpurascens', group: 'Bird' },
  { commonName: 'Plain Chachalaca', scientificName: 'Ortalis vetula', group: 'Bird' },
  { commonName: 'Gray-headed Chachalaca', scientificName: 'Ortalis cinereiceps', group: 'Bird' },
  { commonName: 'Sungrebe', scientificName: 'Heliornis fulica', group: 'Bird' },
  { commonName: 'Limpkin', scientificName: 'Aramus guarauna', group: 'Bird' },
  { commonName: 'Sunbittern', scientificName: 'Eurypyga helias', group: 'Bird' },
  { commonName: 'Gray-necked Wood-Rail', scientificName: 'Aramides cajaneus', group: 'Bird' },
  { commonName: 'Purple Gallinule', scientificName: 'Porphyrio martinica', group: 'Bird' },
  { commonName: 'Northern Jacana', scientificName: 'Jacana spinosa', group: 'Bird' },
  { commonName: 'Southern Lapwing', scientificName: 'Vanellus chilensis', group: 'Bird' },
  { commonName: 'Killdeer', scientificName: 'Charadrius vociferus', group: 'Bird' },
  { commonName: 'Black-necked Stilt', scientificName: 'Himantopus mexicanus', group: 'Bird' },
  { commonName: 'Whimbrel', scientificName: 'Numenius phaeopus', group: 'Bird' },
  { commonName: 'Spotted Sandpiper', scientificName: 'Actitis macularius', group: 'Bird' },
  { commonName: 'Laughing Gull', scientificName: 'Leucophaeus atricilla', group: 'Bird' },
  { commonName: 'Royal Tern', scientificName: 'Thalasseus maximus', group: 'Bird' },
  { commonName: 'Magnificent Frigatebird', scientificName: 'Fregata magnificens', group: 'Bird' },
  { commonName: 'Brown Booby', scientificName: 'Sula leucogaster', group: 'Bird' },
  { commonName: 'Blue-footed Booby', scientificName: 'Sula nebouxii', group: 'Bird' },
  { commonName: 'Brown Pelican', scientificName: 'Pelecanus occidentalis', group: 'Bird' },
  { commonName: 'Neotropic Cormorant', scientificName: 'Nannopterum brasilianum', group: 'Bird' },
  { commonName: 'Anhinga', scientificName: 'Anhinga anhinga', group: 'Bird' },
  { commonName: 'Boat-billed Heron', scientificName: 'Cochlearius cochlearius', group: 'Bird' },
  { commonName: 'Great Blue Heron', scientificName: 'Ardea herodias', group: 'Bird' },
  { commonName: 'Great Egret', scientificName: 'Ardea alba', group: 'Bird' },
  { commonName: 'Snowy Egret', scientificName: 'Egretta thula', group: 'Bird' },
  { commonName: 'Little Blue Heron', scientificName: 'Egretta caerulea', group: 'Bird' },
  { commonName: 'Tricolored Heron', scientificName: 'Egretta tricolor', group: 'Bird' },
  { commonName: 'Cattle Egret', scientificName: 'Bubulcus ibis', group: 'Bird' },
  { commonName: 'Green Heron', scientificName: 'Butorides virescens', group: 'Bird' },
  { commonName: 'Agami Heron', scientificName: 'Agamia agami', group: 'Bird' },
  { commonName: 'Yellow-crowned Night Heron', scientificName: 'Nyctanassa violacea', group: 'Bird' },
  { commonName: 'Black-crowned Night Heron', scientificName: 'Nycticorax nycticorax', group: 'Bird' },
  { commonName: 'Bare-throated Tiger Heron', scientificName: 'Tigrisoma mexicanum', group: 'Bird' },
  { commonName: 'Roseate Spoonbill', scientificName: 'Platalea ajaja', group: 'Bird' },
  { commonName: 'White Ibis', scientificName: 'Eudocimus albus', group: 'Bird' },
  { commonName: 'Green Ibis', scientificName: 'Mesembrinibis cayennensis', group: 'Bird' },
  { commonName: 'Wood Stork', scientificName: 'Mycteria americana', group: 'Bird' },
  { commonName: 'Jabiru', scientificName: 'Jabiru mycteria', group: 'Bird' },
  { commonName: 'Muscovy Duck', scientificName: 'Cairina moschata', group: 'Bird' },
  { commonName: 'Blue-winged Teal', scientificName: 'Spatula discors', group: 'Bird' },
  { commonName: 'Black-bellied Whistling Duck', scientificName: 'Dendrocygna autumnalis', group: 'Bird' },
  { commonName: 'Pale-vented Pigeon', scientificName: 'Patagioenas cayennensis', group: 'Bird' },
  { commonName: 'Scaled Pigeon', scientificName: 'Patagioenas speciosa', group: 'Bird' },
  { commonName: 'Red-billed Pigeon', scientificName: 'Patagioenas flavirostris', group: 'Bird' },
  { commonName: 'Band-tailed Pigeon', scientificName: 'Patagioenas fasciata', group: 'Bird' },
  { commonName: 'Ruddy Ground Dove', scientificName: 'Columbina talpacoti', group: 'Bird' },
  { commonName: 'White-tipped Dove', scientificName: 'Leptotila verreauxi', group: 'Bird' },
  { commonName: 'Ruddy Quail-Dove', scientificName: 'Geotrygon montana', group: 'Bird' },
  { commonName: 'Squirrel Cuckoo', scientificName: 'Piaya cayana', group: 'Bird' },
  { commonName: 'Yellow-billed Cuckoo', scientificName: 'Coccyzus americanus', group: 'Bird' },
  { commonName: 'Groove-billed Ani', scientificName: 'Crotophaga sulcirostris', group: 'Bird' },
  { commonName: 'Smooth-billed Ani', scientificName: 'Crotophaga ani', group: 'Bird' },
  { commonName: 'Greater Ani', scientificName: 'Crotophaga major', group: 'Bird' },
  { commonName: 'Common Potoo', scientificName: 'Nyctibius griseus', group: 'Bird' },
  { commonName: 'Great Potoo', scientificName: 'Nyctibius grandis', group: 'Bird' },
  { commonName: 'Pauraque', scientificName: 'Nyctidromus albicollis', group: 'Bird' },
  { commonName: 'Common Nighthawk', scientificName: 'Chordeiles minor', group: 'Bird' },
  { commonName: 'White-collared Swift', scientificName: 'Streptoprocne zonaris', group: 'Bird' },
  { commonName: "Vaux's Swift", scientificName: 'Chaetura vauxi', group: 'Bird' },
  { commonName: 'Barn Owl', scientificName: 'Tyto alba', group: 'Bird' },
  { commonName: 'Tropical Screech Owl', scientificName: 'Megascops choliba', group: 'Bird' },
  { commonName: 'Bare-shanked Screech Owl', scientificName: 'Megascops clarkii', group: 'Bird' },
  { commonName: 'Spectacled Owl', scientificName: 'Pulsatrix perspicillata', group: 'Bird' },
  { commonName: 'Great Horned Owl', scientificName: 'Bubo virginianus', group: 'Bird' },
  { commonName: 'Mottled Owl', scientificName: 'Ciccaba virgata', group: 'Bird' },
  { commonName: 'Black-and-white Owl', scientificName: 'Ciccaba nigrolineata', group: 'Bird' },
  { commonName: 'Ferruginous Pygmy Owl', scientificName: 'Glaucidium brasilianum', group: 'Bird' },
  { commonName: 'Costa Rican Pygmy Owl', scientificName: 'Glaucidium costaricanum', group: 'Bird' },
  { commonName: 'Slaty-tailed Trogon', scientificName: 'Trogon massena', group: 'Bird' },
  { commonName: 'Black-tailed Trogon', scientificName: 'Trogon melanurus', group: 'Bird' },
  { commonName: "Baird's Trogon", scientificName: 'Trogon bairdii', group: 'Bird' },
  { commonName: 'Black-headed Trogon', scientificName: 'Trogon melanocephalus', group: 'Bird' },
  { commonName: 'Gartered Trogon', scientificName: 'Trogon caligatus', group: 'Bird' },
  { commonName: 'Collared Trogon', scientificName: 'Trogon collaris', group: 'Bird' },
  { commonName: 'Orange-bellied Trogon', scientificName: 'Trogon aurantiiventris', group: 'Bird' },
  { commonName: 'Black-throated Trogon', scientificName: 'Trogon rufus', group: 'Bird' },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Species.deleteMany({});
  await Species.insertMany(species);
  console.log(`Seeded ${species.length} species.`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
